### ISSUE TITLE
Geçerli bir eposta girmezsem ne olacak?

### ISSUE THREAD

**Issue by emir** [yunuselci/PHP-SESSION#1]
https://github.com/yunuselci/PHP-SESSION/blob/be2725ed479f8f03b52943afdf9b98b484b88ace/sign_up.php#L20

Burada sadece boş olup olmadığına bakmışsın. Geçerli bir eposta adresi yazmazsam ne olacak?

Bunu yaparken FILTER_VARIABLE_* fonksiyonlarına bakabilirsin: https://www.php.net/manual/tr/filter.filters.validate.php

**Comment by yunuselci** [comment]
FILTER_VARIABLE_ ile benim kullanımım arasındaki farka bakacağım abi,teşekkür ederim, ben Html içerisinde bulunan input type=email'i kullandığım için geçersiz e posta adreslerinde aşşağıdaki gibi hata alıcaksınız
![image](https://user-images.githubusercontent.com/56027479/69651708-8cf65180-1081-11ea-90a7-103769a0c9bb.png)
![image](https://user-images.githubusercontent.com/56027479/69651732-97185000-1081-11ea-9d29-bf25b83350db.png)

**Comment by emir** [comment]
input'un type'ı konsol'dan değiştirilip gönderebilirsin. front-end tarafında yaptığın hiçbir doğrulamaya güvenmemelisin. hep backend'den kontrol etmelisin.

**Comment by yunuselci** [comment]
![image](https://user-images.githubusercontent.com/56027479/69653581-80272d00-1084-11ea-81f6-633ad0573ffa.png)
Güncellemesi yapıldı

**Comment by emir** [comment]
Eline sağlık. Düzelttikçe commit atıp hashini buraya kopyarlarsan takip ederiz.

**Comment by yunuselci** [comment]
Kullanıcının geçerli bir email girip girmediğini backendde de kontrol ediyoruz artık
commit $hash = c17092d6cb8eeff450bf3e411aa0271096f0a79f
