### ISSUE TITLE
Bütün hataları tek seferde gösterebilirsin

### ISSUE THREAD

**Issue by emir** [yunuselci/PHP-SESSION#2]
https://github.com/yunuselci/PHP-SESSION/blob/be2725ed479f8f03b52943afdf9b98b484b88ace/sign_up.php#L12

Hataları bir yerde toplayıp kullanıcıya çoklu gösterebilirsin.

**Comment by yunuselci** [comment]
![image](https://user-images.githubusercontent.com/56027479/69653619-9208d000-1084-11ea-93bb-fa3328b900e4.png)
Güncellemesi yapıldı

**Comment by emir** [comment]
böyle yaparsan gerekli alanların hangisi olduğunu kullanıcıya nasıl söylersin?

**Comment by yunuselci** [comment]
Artık bütün hatalar bir arayde toplanıp, kullanıcıya tek tek gösteriliyor
commit $hash = c17092d6cb8eeff450bf3e411aa0271096f0a79f
