### ISSUE TITLE
Form'a name atanabilir

### ISSUE THREAD

**Issue by emir** [yunuselci/PHP-SESSION#3]
https://github.com/yunuselci/PHP-SESSION/blob/be2725ed479f8f03b52943afdf9b98b484b88ace/sign_up.php#L71

Burada hidden input göndermek yerine form'a name atayıp onun mu geldiğini kontrol edebilirsin.

**Comment by yunuselci** [comment]
Hidden inputları kaldırdım abi $hash = 9f9f2b66ab6730036a079db999e47a33458ceeae
