### ISSUE TITLE
Linkler linktir, butonlar button

### ISSUE THREAD

**Issue by emir** [yunuselci/PHP-SESSION#4]
https://github.com/yunuselci/PHP-SESSION/blob/be2725ed479f8f03b52943afdf9b98b484b88ace/index.php#L17

onClick vermek yerine linki link, butonu buton niyetiyle kullanmaya başlayabilirsin

**Comment by yunuselci** [comment]
onClick vermeyi bıraktım.Butonları buton, linkleri link olarak kullanmaya çalışıyorum artık $hash = 759d38fe443ebe0e3128693e0005163879c0a185
