### ISSUE TITLE
Boostrap eklenebilir

### ISSUE THREAD

**Issue by emir** [yunuselci/PHP-SESSION#5]
Projene Bootstrap ekleyip basit bir arayüz ile çalışabilirsin: https://getbootstrap.com/

**Comment by yunuselci** [comment]
![image](https://user-images.githubusercontent.com/56027479/69674566-ccd32e00-10ad-11ea-9d54-35d921ec7481.png)
Hazır kodlar kullanarak eklemeye başladım

**Comment by yunuselci** [comment]
Bootstrap eklendi $hash = 9f9f2b66ab6730036a079db999e47a33458ceeae
