### ISSUE TITLE
Kullanıcılara teknik mesaj göstermemelisin ama sen de orada hata olduğunu bilmelisin

### ISSUE THREAD

**Issue by emir** [yunuselci/PHP-SESSION#6]
https://github.com/yunuselci/PHP-SESSION/blob/be2725ed479f8f03b52943afdf9b98b484b88ace/sign_up.php#L44

Son kullanıcılara MySQL error gösterirsen ne olduğunu anlayamaz. Ama sen de orada bir hata olduğunu görmeli takip etmelisin. Denklemi çöz bakalım :)

**Comment by yunuselci** [comment]
Error.log tarzı bir şeyler oluşturmaya bakacağım ama basit bir çözüm olarak local de errors.txt diye bir dosyanın içerisine hataları toplayıp, son kullanıcıya "Bir şeyler ters gitti" şeklinde mesaj vermeye çalıştım commit $hash = 759d38fe443ebe0e3128693e0005163879c0a185
